name: lint

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
